parallel-jobs = 10
remove-rv-integrations-checks = true

# ReVanced Extended by anddea

[YouTube-Morphe]
app-name = "YouTube Morphe"
##archive-dlurl = "https://archive.org/download/com.google.android.youtube-20.25.37-1555295680-min-api-26arm-64-v-8aarmeabi-v-7a/com.google.android.youtube/"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
direct-dlurl = "https://github.com/SharathGames1/APKs/releases/download/4/com.google.android.youtube-20.47.62-all.apk"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
patches-version = "dev"
cli-version = "latest"
excluded-patches = "'Change header'"
patcher-args = "-e 'Custom branding' -OcustomName='YouTube Morphe'  -e 'Theme' -OdarkThemeBackgroundColor=#000000"
build-mode = "both"
#enabled= "false"

#hoo-dles

[PrimeVideo]
app-name="Prime Video"
uptodown-dlurl = "https://amazon-video.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/amazon-mobile-llc/amazon-prime-video/"
patches-source = "hoo-dles/morphe-patches"
build-mode = "apk"
included-patches = "'Skip ads' 'Enable speed control'"
exclusive-patches = true
cli-source = "MorpheApp/morphe-cli"
patches-version = "dev"
cli-version = "latest"
#enabled=false

[Twitter]
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
included-patches = "'Dynamic color'"
cli-source = "MorpheApp/morphe-cli"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"
patches-version = "dev"
cli-version = "latest"
build-mode = "apk"
patches-source = "crimera/piko"
patcher-args = "--continue-on-error"
version = "11.81.0-release.0"

[Instagram]
apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram/"
uptodown-dlurl = "https://instagram.en.uptodown.com/android"
direct-dlurl = "https://github.com/SharathGames1/APKs/releases/download/5/com.instagram.android-426.0.0.37.68-all.apk"
#excluded-patches = "'Change version code'"
cli-source = "MorpheApp/morphe-cli"
patches-version = "dev"
cli-version = "latest"
build-mode = "apk"
patches-source = "crimera/piko"
#enabled = "false"


